# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapWedget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('market_cap', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('volume_24', models.TextField(null=True)),
                ('circulatory_supply', models.TextField(null=True)),
                ('change', models.TextField(null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
