# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180519_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyGraph_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('market_cap', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('volume_24', models.TextField(null=True)),
                ('circulatory_supply', models.TextField(null=True)),
                ('change', models.TextField(null=True)),
                ('symbol', models.TextField(null=True)),
                ('available_supply', models.TextField(null=True)),
                ('total_supply', models.TextField(null=True)),
                ('max_supply', models.TextField(null=True)),
                ('percent_change_1h', models.TextField(null=True)),
                ('percent_change_24h', models.TextField(null=True)),
                ('percent_change_7d', models.TextField(null=True)),
                ('last_update', models.TextField(null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
